if(NOT DEFINED SFLD OR NOT DEFINED SOURCE_DIR OR NOT DEFINED WORK_DIR)
  message(FATAL_ERROR "Missing CLI test paths")
endif()
file(MAKE_DIRECTORY "${WORK_DIR}")
configure_file("${SOURCE_DIR}/profiles/synthetic.profile" "${WORK_DIR}/input.profile" COPYONLY)
set(profile "${WORK_DIR}/input.profile")
file(SHA256 "${profile}" original_hash)
foreach(option IN ITEMS --trace --output)
  execute_process(COMMAND "${SFLD}" simulate --profile "${profile}" --allow-assumptions
    --runs 1 ${option} "${profile}" RESULT_VARIABLE status OUTPUT_QUIET ERROR_QUIET)
  if(NOT status EQUAL 1)
    message(FATAL_ERROR "CLI allowed overwriting its input via ${option}")
  endif()
  file(SHA256 "${profile}" after_hash)
  if(NOT original_hash STREQUAL after_hash)
    message(FATAL_ERROR "Profile contents changed")
  endif()
endforeach()
execute_process(COMMAND "${SFLD}" simulate --profile "${profile}" --allow-assumptions
  --runs 1 --trace "${WORK_DIR}/same.txt" --output "${WORK_DIR}/same.txt"
  RESULT_VARIABLE status OUTPUT_QUIET ERROR_QUIET)
if(NOT status EQUAL 1)
  message(FATAL_ERROR "CLI accepted overlapping trace/report paths")
endif()
execute_process(COMMAND "${SFLD}" simulate --profile "${profile}" --allow-assumptions
  --runs 1 --seed 42 --trace "${WORK_DIR}/run.tsv" --output "${WORK_DIR}/run.json"
  RESULT_VARIABLE status ERROR_VARIABLE details)
if(NOT status EQUAL 0)
  message(FATAL_ERROR "Simulation failed: ${details}")
endif()
file(READ "${WORK_DIR}/run.json" report)
string(JSON evidence GET "${report}" evidence)
string(JSON calibrated GET "${report}" calibrated_to_live_game)
string(JSON spend GET "${report}" mean_mushrooms_per_started_run)
if(NOT evidence STREQUAL "synthetic" OR calibrated OR NOT spend EQUAL 0)
  message(FATAL_ERROR "Invalid scenario/spending report")
endif()
execute_process(COMMAND "${SFLD}" replay --profile "${profile}" --allow-assumptions
  --trace "${WORK_DIR}/run.tsv" RESULT_VARIABLE status ERROR_VARIABLE details)
if(NOT status EQUAL 0)
  message(FATAL_ERROR "CLI replay failed: ${details}")
endif()
