if(NOT DEFINED SFLD OR NOT DEFINED SOURCE_DIR OR NOT DEFINED WORK_DIR)
  message(FATAL_ERROR "Missing CLI test paths")
endif()
file(MAKE_DIRECTORY "${WORK_DIR}")
configure_file("${SOURCE_DIR}/profiles/synthetic.profile" "${WORK_DIR}/input.profile" COPYONLY)
set(profile "${WORK_DIR}/input.profile")
file(SHA256 "${profile}" original_hash)
foreach(option IN ITEMS --trace --output)
  execute_process(COMMAND "${SFLD}" simulate --profile "${profile}" --allow-assumptions
    --runs 1 ${option} "${profile}" RESULT_VARIABLE status OUTPUT_QUIET ERROR_QUIET)
  if(NOT status EQUAL 1)
    message(FATAL_ERROR "CLI allowed overwriting its input via ${option}")
  endif()
  file(SHA256 "${profile}" after_hash)
  if(NOT original_hash STREQUAL after_hash)
    message(FATAL_ERROR "Profile contents changed")
  endif()
endforeach()
execute_process(COMMAND "${SFLD}" simulate --profile "${profile}" --allow-assumptions
  --runs 1 --trace "${WORK_DIR}/same.txt" --output "${WORK_DIR}/same.txt"
  RESULT_VARIABLE status OUTPUT_QUIET ERROR_QUIET)
if(NOT status EQUAL 1)
  message(FATAL_ERROR "CLI accepted overlapping trace/report paths")
endif()
execute_process(COMMAND "${SFLD}" simulate --profile "${profile}" --allow-assumptions
  --runs 1 --seed 42 --trace "${WORK_DIR}/run.tsv" --output "${WORK_DIR}/run.json"
  RESULT_VARIABLE status ERROR_VARIABLE details)
if(NOT status EQUAL 0)
  message(FATAL_ERROR "Simulation failed: ${details}")
endif()
file(READ "${WORK_DIR}/run.json" report)
string(JSON evidence GET "${report}" evidence)
string(JSON calibrated GET "${report}" calibrated_to_live_game)
string(JSON spend GET "${report}" mean_mushrooms_per_started_run)
if(NOT evidence STREQUAL "synthetic" OR calibrated OR NOT spend EQUAL 0)
  message(FATAL_ERROR "Invalid scenario/spending report")
endif()
execute_process(COMMAND "${SFLD}" replay --profile "${profile}" --allow-assumptions
  --trace "${WORK_DIR}/run.tsv" RESULT_VARIABLE status ERROR_VARIABLE details)
if(NOT status EQUAL 0)
  message(FATAL_ERROR "CLI replay failed: ${details}")
endif()

file(REMOVE "${WORK_DIR}/template.state")
execute_process(COMMAND "${SFLD}" state-template --output "${WORK_DIR}/template.state"
  RESULT_VARIABLE status ERROR_VARIABLE details)
if(NOT status EQUAL 0)
  message(FATAL_ERROR "Template creation failed: ${details}")
endif()
execute_process(COMMAND "${SFLD}" audit --profile "${profile}" --state "${WORK_DIR}/template.state"
  RESULT_VARIABLE status ERROR_VARIABLE details)
if(NOT status EQUAL 0)
  message(FATAL_ERROR "Generated template cannot be loaded: ${details}")
endif()
configure_file("${SOURCE_DIR}/examples/gem-choice.state" "${WORK_DIR}/progress.state" COPYONLY)
set(progress "${WORK_DIR}/progress.state")
file(SHA256 "${progress}" progress_hash)
foreach(option IN ITEMS --trace --output)
  execute_process(COMMAND "${SFLD}" simulate --profile "${profile}" --state "${progress}" --allow-assumptions
    --runs 1 ${option} "${progress}" RESULT_VARIABLE status OUTPUT_QUIET ERROR_QUIET)
  file(SHA256 "${progress}" after_hash)
  if(NOT status EQUAL 1 OR NOT after_hash STREQUAL progress_hash)
    message(FATAL_ERROR "CLI did not protect progress input from ${option}")
  endif()
endforeach()
execute_process(COMMAND "${SFLD}" simulate --profile "${profile}" --state "${progress}" --allow-assumptions
  --run-number 1 --runs 1 RESULT_VARIABLE status OUTPUT_QUIET ERROR_QUIET)
if(NOT status EQUAL 1)
  message(FATAL_ERROR "Conflicting run numbers should be rejected")
endif()
execute_process(COMMAND "${SFLD}" compare --profile "${profile}" --state "${progress}" --allow-assumptions
  --sweep gems --runs 8 --threads 2 --output "${WORK_DIR}/gem-comparison.json"
  RESULT_VARIABLE status ERROR_VARIABLE details)
if(NOT status EQUAL 0)
  message(FATAL_ERROR "Progress comparison failed: ${details}")
endif()
file(READ "${WORK_DIR}/gem-comparison.json" report)
string(JSON count LENGTH "${report}" experiments)
string(JSON room GET "${report}" experiments 0 starting_state room)
string(JSON run_number GET "${report}" experiments 0 run_number_within_event)
if(NOT count EQUAL 4 OR NOT room EQUAL 51 OR NOT run_number EQUAL 2)
  message(FATAL_ERROR "Gem sweep did not use the three observed offers and progress")
endif()
execute_process(COMMAND "${SFLD}" simulate --profile "${profile}" --state "${progress}" --allow-assumptions
  --runs 1 --trace "${WORK_DIR}/progress.tsv" --output "${WORK_DIR}/progress.json"
  RESULT_VARIABLE status ERROR_VARIABLE details)
if(NOT status EQUAL 0)
  message(FATAL_ERROR "Progress trace failed: ${details}")
endif()
file(REMOVE "${progress}")
execute_process(COMMAND "${SFLD}" replay --profile "${profile}" --allow-assumptions
  --trace "${WORK_DIR}/progress.tsv" RESULT_VARIABLE status ERROR_VARIABLE details)
if(NOT status EQUAL 0)
  message(FATAL_ERROR "Progress replay should not need its original input file: ${details}")
endif()

execute_process(COMMAND "${SFLD}" compare --profile "${profile}" --allow-assumptions
  --state "${SOURCE_DIR}/examples/shop.state" --sweep shops --budget 10 --recovery-budget 0 --rerolls 5
  --runs 32 --threads 2 --output "${WORK_DIR}/shop-comparison.json"
  RESULT_VARIABLE status ERROR_VARIABLE details)
if(NOT status EQUAL 0)
  message(FATAL_ERROR "Shop-policy comparison failed: ${details}")
endif()
file(READ "${WORK_DIR}/shop-comparison.json" report)
string(JSON count LENGTH "${report}" experiments)
string(JSON target GET "${report}" experiments 3 shop_policy)
if(NOT count EQUAL 4 OR NOT target STREQUAL "one-hit-8")
  message(FATAL_ERROR "Missing no-reroll baseline or target shop strategies")
endif()
foreach(index RANGE 0 3)
  string(JSON healing GET "${report}" experiments ${index} mean_recovery_mushrooms)
  string(JSON spend GET "${report}" experiments ${index} mean_mushrooms_per_started_run)
  string(JSON strength GET "${report}" experiments ${index} shop_strong_effect_probability)
  if(NOT healing EQUAL 0 OR spend GREATER 10 OR NOT strength EQUAL 0.5)
    message(FATAL_ERROR "Shop comparison violated budget, recovery cap or strength assumptions")
  endif()
endforeach()
foreach(option IN ITEMS --shop-policy --recovery-budget)
  execute_process(COMMAND "${SFLD}" simulate --profile "${profile}" --allow-assumptions
    --runs 1 ${option} invalid RESULT_VARIABLE status OUTPUT_QUIET ERROR_QUIET)
  if(NOT status EQUAL 1)
    message(FATAL_ERROR "CLI accepted invalid ${option}")
  endif()
endforeach()
